### ISSUE TITLE
Split Content component into two seperate components...

### ISSUE THREAD

**Issue by robertjeffs** [DeftCorgi/PP1_2018#34]
### Suggestion
The Content component is the router component essentially, but lacks the separation of routes for authenticated users vs unauthenticated users. I want to suggest we split the component into two: PublicRoutes and ProtectedRoutes.

`./src/components/Content.js`

```
/**
 * PublicRoutes - router for landing, login and register routes, redirect user to
 * landing page if any other route.
 */
export const PublicRoutes = () => {
  return (
    <BrowserRouter>
      <Switch>
        <Route path="/" component={LandingView} />
        <Route exact path="/login" component={LoginView}/>
        <Route exact path="/register" component={RegisterView}/>
        <Redirect to="/"/>
      </Switch>
    </BrowserRouter>
  )
}
```

```
/**
 * ProtectedRoutes - router for user's who are authenticated, redirect user's
 * if they try to access login and register pages to the Home page, and
 * redirects any other route not listed to the not found page.
 */
export const ProtectedRoutes = () => {
  return (
    <BrowserRouter>
      <Switch>
        {/* Redirect */}
        <Route exact path="/login" render={() => <Redirect to="/" />} />
        <Route exact path="/register" render={() => <Redirect to="/" />} />
        
        {/* Render */}
        <Route path="/" component={HomeView} />

        <Route exact path="/matches" component={MathesView} />
        <Route exact path="/pending" component={PendingView} />
        <Route exact path="/settings" component={SettingsView} />
        <Route exact path="/auth/logout" component={LogoutView} />

        <Route path="*" component={NotFoundView}/>
      </Switch>
    </BrowserRouter>
  )
}
```

`./App.js`
And below could be how the flow of the App component could be. Sorry I cbb coding it fully 🍔 
```
const App = () => {
  if (AppUserStore.isAuthenticated) {
    return <ProtectedRoutes />;
  }
  return <PublicRoutes />;
};
```

Note: I appended View to page components to be more clear.

### Reason
This will simplify routing when dealing with authenticated users vs unauthenticated users. 

### Alternative
Create a routes.js file at ./src with PublicRoutes and ProtectedRoutes components, and import them into ./src/components/Content.js.

```
const Content = ({ user }) => {
  if (user) {
    return (
      <main className="Content">
        <ProtectedRoutes />
      </main>
    );
  }
  return (
    <main className="Content">
      <PublicRoutes />
    </main>
  );
};
```

**Comment by DeftCorgi** [comment]
As discussed in the meeting, we will follow the alternative suggestion of 
1. separating the routes 
2. moving the routes to the /src/ folder
3. importing the routes into the Content component 

This way we can have cleaner separation of authenticated vs unauthenticated routes / place more importance on the routes component and not have to change too much code.
